### ISSUE TITLE
arm64: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by lmangani** [metrico/libchdb#3]
The arm64 builds of `libchdb.so` are succeeding without errors, but library invocations fail

```
libchdb.so: cannot allocate memory in static TLS block
```

Not sure if this can/should be solved at build stage or with include changes. Any Help welcome!

**Comment by lmangani** [comment]
@auxten any expert mode suggestions? did you see this issue before in chdb? thanks in advance 🙏

**Comment by auxten** [comment]
It's an annoying issue. It cost most of my effort on the chdb v0.11.0 release.
I need to run `gdb` on that arm64 machine to check what happened.
I wondering if `Asahi Linux` on a M1 Macbook can emulate the arm64 Linux.

**Comment by lmangani** [comment]
After some research, the issue seems to be likely related to jemalloc and TLS_MODEL setting in use.
The option `--disable-initial-exec-tls`  or `JEMALLOC_TLS_MODEL` set to `initial-exec` might help but not sure where to fix this in the build process.

**Comment by lmangani** [comment]
Attempted to patch the builder using the same jemalloc settings as the x86 version, but the library now throws an Illegal Instruction error. Anyone able to spare a hand?

**Comment by auxten** [comment]
Try this branch https://github.com/chdb-io/chdb/pull/69

**Comment by lmangani** [comment]
Rebuilt a [new release](https://github.com/metrico/libchdb/releases/download/0.11.4/libchdb_arm64.zip) and tested but still the same error
> Error: /lib/libchdb.so: cannot allocate memory in static TLS block

**Comment by lmangani** [comment]
Resolved
