### ISSUE TITLE
Full API

### ISSUE THREAD

**Issue by husio** [metrico/libchdb#5]
Hi,
I am working on Go bindings for the chdb, and I was wondering where can I find the API definition provided by the shared library. What is in [libchdb.h](https://github.com/metrico/libchdb/blob/main/libchdb.h) seems to be incomplete.

**Comment by lmangani** [comment]
The helper is generally correct. Here's a [fuller example](https://github.com/chdb-io/chdb-node/blob/main/src/addon.cc). Perhaps you can join us contributing to the basic binding we have at [chdb-go](https://github.com/chdb-io/chdb-go)?

**Comment by husio** [comment]
I hoped there is a better API than calling `query_stable` with various flags.

**Comment by lmangani** [comment]
This is mostly driven by the underlying clickhouse APIs but we'd be happy to add better wrappers. Feel free to contribute!
